# Generated by Django 3.2.5 on 2021-07-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privateCommunity', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
