# Generated by Django 3.2 on 2021-07-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20210720_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
